---
# file: roles/homebrew/tasks/homebrew-cask-install.yml

- name: Tap Caskroom
  homebrew_tap: tap=caskroom/cask state=present
  tags:
    - homebrew

- name: Install homebrew-cask
  homebrew: name=brew-cask state=present
  tags:
    - homebrew

- name: Install casks
  homebrew_cask: name={{ item }} state=present
  with_flattened:
    - core_casks
    - casks
  when: item != ""
  tags:
    - homebrew

- name: Modify Alfred scope to include Caskroom in search paths
  shell: brew cask alfred link
  tags:
    - homebrew
