---
# file: roles/homebrew/tasks/homebrew-install.yml
- name: Homebrew is installed?
  stat: path=/usr/local/bin/brew
  register: brew_installed
  tags:
    - homebrew
- debug: var=brew_installed
  tags:
    - debug

- name: Install homebrew
  shell: ruby -e "$(curl -fsSL https://raw.github.com/Homebrew/homebrew/go/install)"
  when: not brew_installed.stat.exists
  tags:
    - homebrew
