---
# file: roles/homebrew/tasks/homebrew-cask-install.yml
- name: Homebrew-cask is installed?
  stat: path=/usr/local/bin/brew-cask.rb
  register: cask_installed
  tags:
    - homebrew
- debug: var=cask_installed
  tags:
    - debug

- name: Install homebrew-cask
  homebrew: name=phinze/cask/brew-cask state=present
  when: not cask_installed.stat.exists
  tags:
    - homebrew

- name: Install casks
  homebrew_cask: name={{ item }} state=present
  with_flattened:
    - core_casks
    - casks
  when: item != ""
  tags:
    - homebrew

- name: Modify Alfred scope to include Caskroom in search paths
  shell: brew cask alfred link
  tags:
    - homebrew
